"""celltraj2 frame-based microscopy trajectory analysis backend."""

from celltraj2.batch import (
    BatchSegmentationSummary,
    JsonlReporter,
    SegmentationBatchJob,
    SegmentationFileJob,
    SegmentationResult,
    run_batch_segmentation,
)
from celltraj2.boundaries import (
    BoundaryGeometryResult,
    BoundaryLibraryResult,
    BoundaryLibraryView,
    BoundaryNeighborResult,
    BoundaryPointSample,
    BoundarySourceSpec,
    BoundaryTransportPlan,
    build_boundary_library,
    compute_boundary_geometry,
    compute_boundary_neighbors,
    common_density_point_samples,
    optimal_transport_plan,
    resolve_boundary_source_ids,
)
from celltraj2.boundary_batch import (
    BatchBoundarySummary,
    BoundaryBatchJob,
    BoundaryFileJob,
    BoundaryGeometryJob,
    BoundaryNeighborJob,
    run_batch_boundaries,
)
from celltraj2.boundary_features import (
    boundary_multipole_magnitudes,
    compute_boundary_feature_frame,
)
from celltraj2.feature_extraction import (
    BatchFeatureExtractionSummary,
    FeatureExtractionBatchJob,
    FeatureExtractionFileJob,
    run_batch_feature_extraction,
)
from celltraj2.features import (
    DEFAULT_MASK_COMPONENT_METRICS,
    FeatureExtractionResult,
    FeatureSetSpec,
    INTENSITY_PERCENTILE_LEVELS,
    INTENSITY_PERCENTILE_STATISTICS,
    INTENSITY_SCALAR_STATISTICS,
    INTENSITY_STATISTIC_OPTIONS,
    MASK_COMPONENT_METRICS,
    REGIONPROPS_SCALAR_PROPERTIES,
    expand_intensity_statistics,
    extract_feature_set,
    mask_components_v1_spec,
    regionprops_v1_spec,
    site_signaling_v1_spec,
)
from celltraj2.h5_access import H5AccessTimeout, H5DependencyChangedError, open_h5
from celltraj2.interpretation import (
    BiologyRelease,
    ClassificationManifest,
    ClassificationResult,
    MaterializationReceipt,
    ProjectObservationKey,
    StateNode,
    StateSpace,
    TypeNode,
    TypeTaxonomy,
    classification_content_digest,
    classification_values_dtype,
    compile_gate_memberships,
    enforce_track_type_constancy,
    observation_spine_digest,
    track_type_review_records,
)
from celltraj2.object_indexing import (
    BatchObjectIndexSummary,
    ObjectIndexBatchJob,
    ObjectIndexFileJob,
    run_batch_object_indexing,
)
from celltraj2.objects import ObjectIndexResult, index_object_set
from celltraj2.registration import (
    RegistrationResult,
    RegistrationSet,
    estimate_pair_translation,
    register_global_translation,
)
from celltraj2.registration_batch import (
    BatchRegistrationSummary,
    RegistrationBatchJob,
    RegistrationFileJob,
    run_batch_registration,
)
from celltraj2.schema import (
    ChannelSpec,
    ImageSourceSpec,
    RoiBounds,
    RoiSpec,
    SegmentationRunSpec,
    TrajectoryMetadata,
)
from celltraj2.store import TrajectoryStore
from celltraj2.surface_motion_batch import (
    BatchSurfaceMotionSummary,
    SurfaceMotionBatchJob,
    SurfaceMotionFileJob,
    run_batch_surface_motion,
)
from celltraj2.tracking import (
    BoundaryMotionResult,
    SparseAdjacency,
    TrackGraph,
    TrackingResult,
    compute_boundary_motion,
    track_minimum_boundary_ot_cost,
    track_minimum_centroid_distance,
)
from celltraj2.tracking_batch import (
    BatchTrackingSummary,
    TrackingBatchJob,
    TrackingFileJob,
    run_batch_tracking,
)
from celltraj2.trajectory import Trajectory

__all__ = [
    "BatchSegmentationSummary",
    "BatchBoundarySummary",
    "BatchTrackingSummary",
    "BatchSurfaceMotionSummary",
    "BatchFeatureExtractionSummary",
    "BatchObjectIndexSummary",
    "BatchRegistrationSummary",
    "BoundaryGeometryResult",
    "BoundaryBatchJob",
    "BoundaryFileJob",
    "BoundaryGeometryJob",
    "BoundaryLibraryResult",
    "BoundaryLibraryView",
    "BoundaryNeighborResult",
    "BoundaryPointSample",
    "BoundaryNeighborJob",
    "BoundaryMotionResult",
    "BoundarySourceSpec",
    "BoundaryTransportPlan",
    "ChannelSpec",
    "FeatureExtractionBatchJob",
    "FeatureExtractionFileJob",
    "FeatureExtractionResult",
    "FeatureSetSpec",
    "DEFAULT_MASK_COMPONENT_METRICS",
    "INTENSITY_PERCENTILE_LEVELS",
    "INTENSITY_PERCENTILE_STATISTICS",
    "INTENSITY_SCALAR_STATISTICS",
    "INTENSITY_STATISTIC_OPTIONS",
    "MASK_COMPONENT_METRICS",
    "REGIONPROPS_SCALAR_PROPERTIES",
    "ImageSourceSpec",
    "H5AccessTimeout",
    "H5DependencyChangedError",
    "BiologyRelease",
    "ClassificationManifest",
    "ClassificationResult",
    "MaterializationReceipt",
    "ProjectObservationKey",
    "StateNode",
    "StateSpace",
    "TypeNode",
    "TypeTaxonomy",
    "JsonlReporter",
    "ObjectIndexBatchJob",
    "ObjectIndexFileJob",
    "ObjectIndexResult",
    "RoiBounds",
    "RoiSpec",
    "RegistrationBatchJob",
    "RegistrationFileJob",
    "RegistrationResult",
    "RegistrationSet",
    "SegmentationBatchJob",
    "SegmentationFileJob",
    "SegmentationResult",
    "SegmentationRunSpec",
    "SparseAdjacency",
    "SurfaceMotionBatchJob",
    "SurfaceMotionFileJob",
    "TrackGraph",
    "TrackingBatchJob",
    "TrackingFileJob",
    "TrackingResult",
    "Trajectory",
    "TrajectoryMetadata",
    "TrajectoryStore",
    "build_boundary_library",
    "boundary_multipole_magnitudes",
    "compute_boundary_feature_frame",
    "compute_boundary_geometry",
    "compute_boundary_neighbors",
    "common_density_point_samples",
    "compute_boundary_motion",
    "classification_content_digest",
    "classification_values_dtype",
    "compile_gate_memberships",
    "enforce_track_type_constancy",
    "expand_intensity_statistics",
    "extract_feature_set",
    "estimate_pair_translation",
    "index_object_set",
    "mask_components_v1_spec",
    "optimal_transport_plan",
    "open_h5",
    "observation_spine_digest",
    "resolve_boundary_source_ids",
    "regionprops_v1_spec",
    "register_global_translation",
    "run_batch_registration",
    "run_batch_boundaries",
    "run_batch_object_indexing",
    "run_batch_feature_extraction",
    "run_batch_segmentation",
    "run_batch_tracking",
    "run_batch_surface_motion",
    "site_signaling_v1_spec",
    "track_minimum_boundary_ot_cost",
    "track_minimum_centroid_distance",
    "track_type_review_records",
]

__version__ = "0.1.0"
